spring:
  application:
    name: AnvilCord
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: INFO
    io.github.yvancywan.anvilcord: DEBUG
    discord4j: INFO
    reactor.netty: WARN
