spring:
  application:
    name: AnvilCord
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: INFO
    com.yvan.cywan.anvilcord: DEBUG
    discord4j: INFO
    reactor.netty: WARN
